version: '3.7'
services:
  redis:
    container_name: redis_bot_container
    build:
      context: buildfiles
      dockerfile: redis.dockerfile
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - app_network
  db:
    container_name: postgres_bot_container
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - app_network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "yaroslav.dvoinyh@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Cbyufgeh115"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - app_network
  bot:
    container_name: bot_container
    build: .
    env_file:
      - ./.env
    command: sh -c "alembic upgrade head && python -m src.bot"
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - app_network
volumes:
  pgdata:
  pgadmin-data:

networks:
  app_network:
    driver: bridge